# PV for config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  labels:
    app: jellyfin
    name: nfs-volume
    part-of: jellyfin-data
    created-by: miwwge
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: 10.1.1.11
    path: /data/configs/jellyfin
    readOnly: false
# PV for Media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  labels:
    app: jellyfin
    name: smb-volume
    part-of: jellyfin-data
    created-by: miwwge
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  storageClassName: smb
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  mountOptions:
    - dir_mode=0744
    - file_mode=0644
    - uid=1000
    - gid=1000
    - rw
    - noperm
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: jellyfin-media
    volumeAttributes:
      source: "//10.1.1.20/Media"
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
# PVC for Config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  labels:
    app: jellyfin
    name: nfs-volume-claim
    part-of: jellyfin-data
    created-by: miwwge
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: jellyfin
  volumeName: jellyfin-config-pv
# PVC for Media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  labels:
    app: jellyfin
    name: smb-volume-claim
    part-of: jellyfin-data
    created-by: miwwge
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: jellyfin
  volumeName: jellyfin-media-pv
# App Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
    name: deployment
    part-of: jellyfin-data
    created-by: miwwge
  name: jellyfin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: linuxserver/jellyfin:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1000m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        ports:
        - name: http-web-ui
          containerPort: 8096
          protocol: TCP
        - name: https-web-ui
          containerPort: 8920
          protocol: TCP
        - name: net-discovery
          containerPort: 7359
          protocol: UDP
        - name: dnla-discovery
          containerPort: 1900
          protocol: UDP
        volumeMounts:
        - name: jellyfin-config-volume
          mountPath: /config
        - name: jellyfin-media-volume
          mountPath: /media
      securityContext:
        fsGroup: 1000
      volumes:
      - name: jellyfin-config-volume
        persistentVolumeClaim:
          claimName: jellyfin-config-pvc
      - name: jellyfin-media-volume
        persistentVolumeClaim:
          claimName: jellyfin-media-pvc
# Service Creation
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
    name: service
    part-of: jellyfin-data
    created-by: miwwge
  name: jellyfin
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: jellyfin
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8096
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8920
  - name: net-discovery
    protocol: UDP
    port: 7359
    targetPort: 7359
  - name: dnla-discovery
    protocol: UDP
    port: 1900
    targetPort: 1900
  loadBalancerIP: 10.1.1.33
